/**
 * TokenTrim icon sprite builder (build-time only — zero runtime requests).
 * Fetches official Material Symbols SVGs (Apache 2.0, (c) Google) and bakes
 * them into an inline <svg> sprite consumed via <use href="#tt-i-…">.
 * SVGs inherit currentColor, so they follow the Rouge & Ivory theme for free.
 *
 * Run: node tools/fetch-icons.js
 * Output: icons-sprite.svg (inlined into popup.html by hand, see below)
 */
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');

const ICONS = [
  'history', 'settings', 'upload_file', 'folder_open', 'description',
  'add_circle', 'picture_as_pdf', 'close', 'bolt', 'memory', 'shield',
  'check_circle', 'terminal', 'verified', 'content_copy', 'done',
  'download', 'refresh', 'tune', 'neurology', 'chat', 'auto_awesome',
  'verified_user', 'info', 'warning', 'error', 'feedback'
];

const BASE = 'https://raw.githubusercontent.com/google/material-design-icons/master/symbols/web';

function toSymbol(name, svg) {
  // Keep viewBox + paths only; force fill=currentColor, drop hardcoded fills.
  const vb = (svg.match(/viewBox="([^"]+)"/) || [])[1] || '0 0 20 20';
  const inner = svg
    .replace(/<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/\sfill="[^"]*"/g, '');
  return `  <symbol id="tt-i-${name}" viewBox="${vb}">${inner}</symbol>`;
}

let symbols = [];
for (const name of ICONS) {
  const url = `${BASE}/${name}/materialsymbolsoutlined/${name}_20px.svg`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`fetch failed ${res.status} for ${name}: ${url}`);
  const svg = await res.text();
  if (!svg.includes('<svg')) throw new Error(`not an svg for ${name}`);
  symbols.push(toSymbol(name, svg));
  console.log(`ok ${name}`);
}

const out = `<!-- TokenTrim icon sprite — Material Symbols (Apache 2.0, Google). Generated by tools/fetch-icons.js. Do not hand-edit. -->\n<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">\n${symbols.join('\n')}\n</svg>\n`;
writeFileSync(join(ROOT, 'icons-sprite.svg'), out);
console.log(`wrote icons-sprite.svg (${symbols.length} symbols)`);
